fix gradle demo
This should work out of the box for the next guy:
added gradle wrapper
fixed gradle build errors for removed attributes
also tried to fix Gradle deprecation warnings so it won't happen again for gradle 7, but then the build stopped acting correctly (compile -> implementation stopped libs from ending up in jars and other oddities)
added pluginsDir system property override to app Gradle build rather than needing it to pass it in
added annotation processing to Gradle build files
should use app:run rather than running the jar directly or you get a NoClassDefFoundError. This also changes the root and plugin directory needs to look in the parent dir.
updated readme with the above changes
updated kotlin version and dependencies

revert gradle deprecation warning fixes